export const skillsWithRatings = [
  { name: 'JavaScript', rating: 9, category: 'Languages' },
  { name: 'TypeScript', rating: 9, category: 'Languages' },
  { name: 'Python', rating: 6, category: 'Languages' },
  { name: 'HTML', rating: 9, category: 'Languages' },
  { name: 'Vite', rating: 9, category: 'Frontend' },
  { name: 'CSS', rating: 9, category: 'Languages' },
  { name: 'Radix', rating: 10, category: 'Frontend' },
  { name: 'SolidJS', rating: 9, category: 'Frontend' },
  { name: 'Sass', rating: 9, category: 'Languages' },
  { name: 'React JS', rating: 9, category: 'Frontend' },
  { name: 'Next JS 14', rating: 9, category: 'Frontend' },
  { name: 'Gatsby JS', rating: 7, category: 'Frontend' },
  { name: 'Redux', rating: 10, category: 'Frontend' },
  { name: 'Tailwind CSS', rating: 10, category: 'Frontend' },
  { name: 'shadcn/ui', rating: 10, category: 'Frontend' },
  { name: 'Material UI', rating: 10, category: 'Frontend' },
  { name: 'Bootstrap', rating: 10, category: 'Frontend' },
  { name: 'Node.js', rating: 6, category: 'Backend' },
  { name: 'Express', rating: 6, category: 'Backend' },
  { name: 'AWS S3', rating: 6, category: 'Backend' },
  { name: 'AWS SageMaker', rating: 6, category: 'Backend' },
  { name: 'GitHub CI/CD', rating: 6, category: 'Backend' },
  { name: 'TypeORM', rating: 6, category: 'Backend' },
  { name: 'Prisma', rating: 6, category: 'Backend' },
  { name: 'SQL', rating: 6, category: 'Backend' },
  { name: 'AWS EFS', rating: 6, category: 'Backend' },
  { name: 'AWS EC2', rating: 6, category: 'Backend' },
  { name: 'Mysql', rating: 6, category: 'Database' },
  { name: 'PostgreSQL', rating: 6, category: 'Database' },
  { name: 'MongoDB', rating: 6, category: 'Database' },
  { name: 'GPT-3.5', rating: 7, category: 'LLM' },
  { name: 'GPT-4', rating: 7, category: 'LLM' },
  { name: 'Llama', rating: 5, category: 'LLM' },
  { name: 'Stable Diffusion', rating: 5, category: 'LLM' },
  { name: 'Prompt Engineering', rating: 7, category: 'LLM' },
  { name: 'Git', rating: 9, category: 'Version Control System' },
  { name: 'GitHub', rating: 9, category: 'Version Control System' },
  { name: 'GitLab', rating: 9, category: 'Version Control System' },
  { name: 'Strapi', rating: 6, category: 'CMS' },
  { name: 'Sanity', rating: 6, category: 'CMS' },
  { name: 'Micro Services', rating: 2, category: 'Currently Exploring' },
  { name: 'Kubernetes', rating: 3, category: 'Currently Exploring' },
  { name: 'Docker', rating: 3, category: 'Currently Exploring' },
  { name: 'Video Based LLM', rating: 2, category: 'Currently Exploring' },
  { name: 'Mistral 7B', rating: 1, category: 'Currently Exploring' },
  { name: 'Mistral', rating: 2, category: 'Currently Exploring' },
  { name: 'Whisper', rating: 2, category: 'Currently Exploring' },
];
