export const skillsWithRatings = [
  { name: 'Javascript', rating: 9, category: 'languages' },
  { name: 'Typescript', rating: 9, category: 'languages' },
  { name: 'Python', rating: 6, category: 'languages' },
  { name: 'Html', rating: 9, category: 'frontend' },
  { name: 'Vite', rating: 9, category: 'frontend' },
  { name: 'Css', rating: 9, category: 'frontend' },
  { name: 'Sass', rating: 9, category: 'frontend' },
  { name: 'React JS', rating: 9, category: 'frontend' },
  { name: 'Next JS 14', rating: 9, category: 'frontend' },
  { name: 'Gatsby Js', rating: 7, category: 'frontend' },
  { name: 'Redux', rating: 10, category: 'frontend' },
  { name: 'Node.js', rating: 6, category: 'backend' },
  { name: 'Express', rating: 6, category: 'backend' },
  { name: 'Aws s3', rating: 6, category: 'backend' },
  { name: 'Aws sagemaker', rating: 6, category: 'backend' },
  { name: 'Aws efs', rating: 6, category: 'backend' },
  { name: 'GPT-3.5', rating: 7, category: 'LLM' },
  { name: 'GPT-4', rating: 7, category: 'LLM' },
  { name: 'Llama', rating: 5, category: 'LLM' },
  { name: 'Stable diffusion', rating: 5, category: 'LLM' },
  { name: 'Prompt engineering', rating: 7, category: 'LLM' },
  { name: 'git', rating: 9, category: 'Version control system' },
  { name: 'github', rating: 9, category: 'Version control system' },
  { name: 'gitlab', rating: 9, category: 'Version control system' },
  { name: 'strapi', rating: 6, category: 'cms' },
  { name: 'sanity', rating: 6, category: 'cms' },
  { name: 'micro services', rating: 2, category: 'Currently exploring' },
  { name: 'Kubernetes', rating: 3, category: 'Currently exploring' },
  { name: 'Docker', rating: 3, category: 'Currently exploring' },
  { name: 'Video based llm', rating: 2, category: 'Currently exploring' },
  { name: 'mistral 7b', rating: 1, category: 'Currently exploring' },
  { name: 'mistral', rating: 2, category: 'Currently exploring' },
  { name: 'Whisper', rating: 2, category: 'Currently exploring' },
];
